// cogitator omp live-attention bridge.
//
// Auto-generated by `cogitator omp-hook install`; placed in
// ~/.omp/agent/extensions/ so omp auto-discovers it for every session. It
// forwards a handful of lifecycle events to a running cogitator TUI by piping a
// small JSON payload to the `cogitator omp-hook` subcommand, which relays it
// over a local Unix-domain socket. When cogitator is not running the subcommand
// exits 0 and the spawn error is ignored, so omp sessions are never blocked or
// slowed.
import { spawn } from "node:child_process";

// Absolute path to the cogitator binary, baked in at install time so the hook
// runner does not depend on inheriting an interactive shell PATH.
const COGITATOR_BIN = "__COGITATOR_BIN__";

function forward(eventName, ctx, extra) {
  try {
    let sessionFile = "";
    try {
      sessionFile = (ctx && ctx.sessionManager && ctx.sessionManager.getSessionFile)
        ? ctx.sessionManager.getSessionFile()
        : "";
    } catch {
      sessionFile = "";
    }

    const payload = JSON.stringify({
      hook_event_name: eventName,
      cwd: (ctx && ctx.cwd) || "",
      session_file: sessionFile || "",
      ...(extra || {}),
    });

    const child = spawn(COGITATOR_BIN, ["omp-hook"], {
      stdio: ["pipe", "ignore", "ignore"],
    });
    // cogitator missing or not running → fire-and-forget, never surface.
    child.on("error", () => {});
    child.stdin.on("error", () => {});
    child.stdin.end(payload);
  } catch {
    // Defensive: a bridge fault must never affect the omp session.
  }
}

export default function cogitatorBridge(pi) {
  pi.on("session_start", (_event, ctx) => forward("session_start", ctx));
  pi.on("turn_start", (_event, ctx) => forward("turn_start", ctx));
  pi.on("turn_end", (_event, ctx) => forward("turn_end", ctx));
  pi.on("session_shutdown", (_event, ctx) => forward("session_shutdown", ctx));

  // The `ask` tool is omp's "waiting for the user" signal — forward only those
  // tool events to keep process churn low.
  pi.on("tool_call", (event, ctx) => {
    if (event && event.toolName === "ask") {
      forward("tool_call", ctx, { tool_name: "ask" });
    }
  });
  pi.on("tool_result", (event, ctx) => {
    if (event && event.toolName === "ask") {
      forward("tool_result", ctx, { tool_name: "ask" });
    }
  });
}
